---
  - hosts: raspberry
    tasks: 
    - name: add groups to user using file placed at host_vars directory
      user:
        name: "{{clearcase_user}}"
        append: yes
        groups: "{{clearcase_groups}}"
...
